title: Site

sections:
  person:
    type: pages
    label: People
    parent: kirby.page("people")
    templates:
      - person
  chapter:
    type: pages
    label: Chapters
    parent: kirby.page("chapters")
    templates:
      - chapter
