title: Site
options:
  delete: false
  changeSlug: false
  changeTitle: false
  changeStatus: false
  changeTemplate: false

sections:
  person:
    type: pages
    label: People
    parent: site.find("people")
    templates:
      - person
  chapter:
    type: pages
    label: Chapters
    parent: kirby.page("chapters")
    templates:
      - chapter
  lesson:
    type: pages
    label: Lessons
    parent: kirby.page("lessons")
    templates:
      - lesson
